spring.datasource.url=jdbc:postgresql://localhost:5432/bank_system_security
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

testing.app.secret=ksdklasj23211kpokkw
testing.app.expirationMs=600000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

server.port=9090